require: rubocop-rspec
inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml
AllCops:
  Exclude:
    - db/schema.rb
    - spec/dummy/**/*
    - node_modules/**/*
    - tmp/**/*
GitHub/RailsControllerRenderLiteral:
  Enabled: false
GitHub/RailsControllerRenderPathsExist:
  Enabled: false
